config/routes.rb
Rails.application.routes.draw do
  get 'home/about'=>'homes#about'
  get 'users/new'
  #patch 'book_paramss/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  root to: "homes#top"
  devise_for :users
  
  resources :books, only: [:new, :create, :index, :show, :edit,:update]
  resources :users, only: [:show, :edit, :index,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   
   
    validates :title, presence: true
    validates :body, presence: true,  length: {  maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_one_attached :profile_image
  
  has_many :books, dependent: :destroy   
  
  validates :name, presence: true,length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,  length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

   # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @books=Book.all
      @user=current_user
      render :index
    end

  end

  def index
    @books = Book.all
    @user=current_user
    @book= Book.new
  end

  def show
    @books=Book.new
    @book = Book.find(params[:id])
    @user =@book.user
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      #redirect_to root_path
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path # 投稿一覧画面へリダイレクト
  end
   # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :image, :body, :destroy)
  end

   def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :correct_user, only: [:edit, :update]
  def new
  end

  def index
    @book=Book.new
    @users = User.all
    @user=current_user
  end

  def show
    
    @user =  User.find(params[:id])
    @books = @user.books
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
     flash[:notice] = "You have updated user successfully."
     
    else
      @users=current_user
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
   def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless @user == current_user
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  
  <div class="container">  <!-- この行を追加 -->
    <div class="row">      <!-- この行を追加 -->
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>


　 <div class="form-group">
      <label for="title">Title</label>
      <%= f.text_field :title,class:"form-control title" %>
      </div>
  
  
   <div class="form-group">
      <label for="body">Opinion</label>
      <%= f.text_area :body,class:"form-control body" %>
      </div>
  
  
  <div class="form-group">
      <%= f.submit "Update Book",class:"btn btn-success updatebook" %>
    <div>
    <%= link_to "Show",book_path(@book.id)%>
    <%= link_to "Back",books_path %>
    </div>
  </div>
  </div>
<% end %>
  </div> 
  </div>   
</main>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>
<main>
  <p id="notice"><%= notice %></p>
  <div class="container  px-5 px-sm-0">

     <div class="row">
      <div class="col-md-3">
         <h1>User Info</h1>


        <%= image_tag @user.get_profile_image(100,100)%>
          <table class="table">
          <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%=@user.introduction%></th>
          </tr>
          </tbody>
          </table>
          <%#= image_tag @user.get_profile_image(100,100) %>



  <!-- この行を追加 -->
        <!-- この行を追加 -->
     <div class="row">
      <%  @user ==  current_user %>
          <%= link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>

      </div>
      <h2>New book</h2>

      <%= form_with model: @book do |f| %>


          <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title,class:"form-control title" %>
          </div>

         <div class="form-group">
    　　　　　　<label for="book_opinion">Opinion</label>
    　　    <%= f.text_area :body,class:"form-control body" %>
  　　　　</div>

          <%#= f.submit '投稿' %>


        <div class="form-group">
　    　　 <%= f.submit "Create Book",class:"btn btn-success createbook" %>
  　　　　</div>

       </div>
        <% end %>


       <!-- この行を追加 -->
        <div class="col-md-8 offset-md-1">
        <h1>Books</h1>


        <table class="table table-hover table-inverse">

        <thead>
            <tr>

              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
        </thead>
              <%#= image_tag book.get_image %>
        <tbody>
            <% @books.each do |book| %>
            <tr>

              <td><%= link_to user_path(book.user) do%>
              <%= image_tag book.user.get_profile_image(100,100)  %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id)  %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

<%#= link_to 'New Book', new_book_path, class: "btn btn-secondary" %>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->


<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<main>
 
  <div class="container">  <!-- この行を追加 -->
    <div class="row">      <!-- この行を追加 -->
      <div class="col-md-3">

　　　<div>
  <%= flash[:notice] %>
　</div>
　<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
　<% end %>


        <h1>User Info</h1>
        
         <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
           <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%=@user.introduction%></th>
          <th></th>
          </tr>
          </tbody>
          </table>
         
          
          <%= link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        
          <% end %>
        
        
        <!-- ユーザーの投稿一覧 -->
        <%#= render 'post_images/list', post_images: @post_images %>
        
              <h2>New book</h2>
         
        <!-- form_with部分 -->
        <%= form_with model: @books do |f| %>
          
        
          <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title,class:"form-control title" %>
          </div>
         
          
          <div class="form-group">
    　　　　　　<label for="book_opinion">Opinion</label>
    　　    <%= f.text_area :body,class:"form-control body" %>
  　　　　　　</div>
        
          <%#= f.submit '投稿' %>
        
        
        <div class="form-group">
　    　　 <%= f.submit "Create Book",class:"btn btn-success createbook" %>
    　　　</div>
        
        
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">  <!-- この行を追加 -->
        <h1>Book detail</h1>
        
        
        <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image(100,100) %>
              <br>
              <%= link_to @user.name, user_path(@user.id) %>
            </td>
          
            <td><%= link_to @book.title, book_path(@book.id)  %></td>
            <td><%= @book.body %></td>
             <% if @book.user == current_user %>
             
             <td><%= link_to "Edit",edit_book_path(@book.id),class: "btn btn-sm btn-success edit_book" %></td>
            
            
             <td><%= link_to "Destroy",destroy_book_path(@book.id) , method: :delete, class:"btn btn-sm btn-danger destroy_book","data-confirm" => "本当に削除しますか？"%></td>
           
            <% end %>
          </tr>
        </tbody>
        </table>
      </div>
    </div> 
  </div>   
</main>
  

app/views/homes/about.html.erb
<main> 
<div class="container">
<div class="row">
<div class="px-3 mx-auto">
<h1>welcome to
<i class="fas fa-book"></i>
Bookers!!</h1>
<br>
</div>
</div>
</div>
</div>
</main>

app/views/homes/top.html.erb
<main>
<p id="notice">Signed out successfully.</p>
<div class="container">
<div class="row">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h2>welcome to
<i class="fas fa-book"></i> 

Bookers!!
</h2>
<br>
  <p>In 
 <i class="fas fa-book"></i> 
  <strong>Bookers</strong>, </p>
  <p>you can share and exchange  your opinions , inpressions , and emotions</p>
  <p> about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
        </div>
      </div>
</div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9b25a5065d.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
    <li>
    <%#= link_to '投稿フォーム', new_book_path %>
  </li>
   <li>
      <%= link_to  user_path(current_user.id),class: "nav-link text-light" do %>
      <i class="fas fa-home"></i> Home
      <% end %>
      </li>
      <li>
        <%= link_to  users_path,class: "nav-link text-light" do %>
        <i class="fas fa-users"></i> Users
        <% end %>
      </li>
      <li>
        <%= link_to  books_path,class: "nav-link text-light"  do %>
       <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li>
        <%= link_to  destroy_user_session_path, method: :delete,class: "nav-link text-light" do %>
        <i class="fas fa-sign-out-alt"></i> Log out
       <% end %>
      </li>
    <% else %>
      <li>
      <%= link_to  root_path,class: "nav-link text-light" do %>
      <i class="fas fa-home"></i> Home
      <% end %>
      </li>

      <li>
        <%= link_to  home_about_path,class: "nav-link text-light" do %>
        <i class="fas fa-link"></i> About
         <% end %>
      </li>
      <li>
        <%= link_to  new_user_registration_path,class: "nav-link text-light" do %>
         <i class="fas fa-user-plus"></i> Sign up
          <% end %>
      </li>
      <li>
        <%= link_to  new_user_session_path,class: "nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i> Log in
         <% end %>
      </li>


    <% end %>
      </ul>
      </div>
      </div>
      </nav>
     </header>
    <%= yield %>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
   </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
 <p id="notice"><%= notice %></p>
  <div class="container">  <!-- この行を追加 -->
    <div class="row">      <!-- この行を追加 -->
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>


<h1>User info</h1>
     
     <% if @user.errors.any? %>
  <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
     
      <div class="form-group">
      <label for="user_name">Name</label>
      <%= f.text_field :name,class:"form-control name" %>
      </div>
      
      
       <div class="form-group">
      <label for="user_image">Image</label>
      <%= f.file_field :profile_image,class:"form-control-file user_image", placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
      
       <div class="form-group">
      <label for="user_introduction">OpinionOpinion</label>
      <%= f.text_area :introduction,class:"form-control introduction" %>
      </div>
      
       <div class="form-group">
       <%= f.submit "Update User",class:"btn btn-secondary" %>
       </div>


      <% end %>
    </div>  
  </div>
  </main>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= notice %></p>
  <div class="container px-5 px-sm-0">  <!-- この行を追加 -->
    <div class="row">      <!-- この行を追加 -->
      <div class="col-md-3">

        <h1>User Info</h1>


          <%= image_tag @user.get_profile_image(100,100)%>
          <table class="table">
          <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%=@user.introduction%></th>
          </tr>
          </tbody>
          </table>
          
          
          
          
          <div class="row"> 
         <% if @user ==  current_user %>
          <%= link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
          <% end %>

        <!-- ユーザーの投稿一覧 -->
        <%#= render 'post_images/list', post_images: @post_images %>

              <h2>New book</h2>

        <!-- form_with部分 -->
        <%= form_with model: @book do |f| %>


          <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title,class:"form-control title" %>
          </div>

         <div class="form-group">
    　　　　　　<label for="book_opinion">Opinion</label>
    　　    <%= f.text_area :body,class:"form-control body" %>
  　      </div>

          <%#= f.submit '投稿' %>


          <div class="form-group">
　    　　 <%= f.submit "Create Book",class:"btn btn-success createbook" %>
    　      </div>

         </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">  <!-- この行を追加 -->
        <h1>Users</h1>


        <table class="table table-hover table-inverse">

        <thead>
            <tr>

              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
        </thead>
              <%#= image_tag book.get_image %>

        <tbody>
           <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to"Show",user_path(user.id) %></td>
          </tr>
          <% end%>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<main>
 <div>
  <%= flash[:notice] %>
   </div>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container px-5 px-sm-0">


    <div class="row">      <!-- この行を追加 -->
      <div class="col-md-3">

        <h1>User Info</h1>

         <%= image_tag @user.get_profile_image(100,100) %>
          <table class="table">
          <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%=@user.introduction%></th>
          </tr>
          </tbody>
          </table>

         <div class="row">
           <%  @user ==  current_user %>
          <%= link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
         </div>
              <h2>New book</h2>
        <%= form_with model: @book do |f| %>


          <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title,class:"form-control title" %>
          </div>

         <div class="form-group">
    　　　　　　<label for="book_opinion">Opinion</label>
    　　    <%= f.text_area :body,class:"form-control body" %>
  　　　　　　</div>


         <div class="form-group">
　    　　 <%= f.submit "Create Book",class:"btn btn-success createbook" %>
    　　　　  </div>
        <% end %>
      </div>


      <div class="col-md-8 offset-md-1">  <!-- この行を追加 -->
        <h1>Books</h1>
        <table class="table table-hover table-inverse">

        <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @books.each do |book| %>
            <tr>
              <td><%#= image_tag book.user.get_profile_image(100,100) %>
              <br>

              </td>
              <td>
              <%= link_to user_path(book.user) do%>
              <%= image_tag book.user.get_profile_image(100,100) %>
              </td>
              </td>
              <%end%>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%#= book.user.name %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</main>